### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by tanner87661** [mrrwa/NmraDcc#22] opened 2019-02-15 16:17 UTC
After successfully running the Accessory test program that is part of the library I started using the code in a larger program. It started crashing as soon as the DCC signal was present, which pointed my look closer into the ISR.

In the process I think I have discovered some problems with the ISR:
a) for ESP32, it should be compiled with the IRAM_ATTR attribute like this: void IRAM_ATTR ExternalInterruptHandler(void)
For more information see here: https://techtutorialsx.com/2017/09/30/esp32-arduino-external-interrupts/
and here: https://github.com/espressif/arduino-esp32/issues/489

b) I also added the MUX line: portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED; and secured the access to the shard data in the ISR and the process routing:
portENTER_CRITICAL_ISR(&mux); DccRx.PacketCopy = DccRx.PacketBuf ; DccRx.DataReady = 1 ; portEXIT_CRITICAL_ISR(&mux);

Unfortunately, while all this is good, it was still crashing as soon as my program tried to access the file system (SPIFFS), eg. for loading config files or a serving a web page.

c) It turns out the real problem is the reattachment of interrupts within the IRS. As soon as I commented those lines out, the program stopped crashing, but unfortunately, it would no longer decode the DCC signals. So I found a workaround and defined a variable ISRWatch which holds the type of interrupt to look for, either falling, raising, or change. Then I replaced all attach interrupt functions by just changing the content of the ISRWatch variable and changed the attacheinterrupt call in the init function to CHANGE. Finally, I added a filter to the beginning of the ISR where I would check the type of interrupt and either return or proceed:

void IRAM_ATTR ExternalInterruptHandler(void)
{
switch (ISRWatch)
{
case CHANGE: break; 
case RISING: if (digitalRead(DccProcState.ExtIntPinNum)) break; 
case FALLING: if (digitalRead(DccProcState.ExtIntPinNum)) return; break; 
}

In this quick fix I did not care about support for other processors etc. So maybe someone with good knowledge of the entire could make the proper adjustments so it works with all processors.

**Comment by kiwi64ajs** [comment] 2019-02-15 19:35
Hi Hans

Can you post your modified code or email it to me please so I can see it in context?

Alex

**Comment by tanner87661** [comment] 2019-02-15 19:42
Hi Alex

 

See attached. Changes are in line 250 and then lines 350-10xx of nmradcc.cpp

I think there are no changes in the header file

 

Best wishes

Hans

**Comment by kiwi64ajs** [comment] 2019-02-16 03:28
Hi Hans,

I’m having trouble to get this to work on the AVR so maybe you’ve missed something so can you email me the actual NmraDcc.h and NmraDcc.cpp files as attachments please?

I seem to get the first packet and then it freezes.

Alex

**Comment by tanner87661** [comment] 2019-02-16 04:27
Hi Alex

 

I just double checked. What I sent you earlier are my current files. Here are the details of my changes:

 

Line 250: Added new variable ISRWatch

Line 305: Added PortMUX_Type

Line 307: Added IRAM_ATTR attribute

Line 309-313: added switch statement to see what type of interrupt we are dealing with and what to do

Line 413: eliminated Interrupt reattachment and just changed interrupt tyupe in ISRWatch

Same in Line 453 and 485

Line 524 and 527: added critical section for access to shared variable 

Line 1352: changed attachinterrupt parameter from RISING to CHANGE

Line 1463 and 1466: added critical section for access to shared variables

 

I would think that for the AVR platform some of these changes will not work, so you need to add conditional compilation, probably even go back to changing the interrupts

That’s it.

Hans

**Comment by kiwi64ajs** [comment] 2019-02-16 09:32
Hi Guys,

I've hand-merged the ESP32 IRAM_ATTR changes and replaced the detach/attachInterrupts code and added the portENTER/EXIT_CRITICAL sections as well. I've pushed the changes on the  ESP32-IRAM_ATTR  branch here: https://github.com/mrrwa/NmraDcc/tree/ESP32-IRAM_ATTR

I've confirmed that the code still works on an AVR, but it would be helpful if some of you were able to confirm that it works on the ESP32 and STM32F1 platforms as well.

Alex

**Comment by MicroBahner** [comment] 2019-02-16 10:03
Hi Alex, Hi Hans
I saw the changes this morning and already had a look at them. I don't think it's a good idea to have these ESP32 related changes of Hans for all processors. We get much more Interrupts than necessary. This may not be a problem with ESP32 because it's considerably faster then AVR, but we should not do the changes generally. I think It is better and 'safer' to make them ESP32 specific and leave the code for the other processors unchanged. 
I try to make a proposal in this sense the next days.

Regards
Franz-Peter

**Comment by MicroBahner** [comment] 2019-02-16 14:52
Hi Hans,
when looking over the code I had another idea. During my tests for the STM32F1 processors I had a similar problem with the reattachment of the interrupts. To get it working I had to explicitly detach it bevor reattaching again. Such as here in the code:
`#if defined ( __STM32F1__ ) `
`     detachInterrupt( DccProcState.ExtIntNum );`
`#endif`
`attachInterrupt( DccProcState.ExtIntNum, ExternalInterruptHandler, CHANGE);`

Did you check whether this could be a solution for ESP32 too? If this works it would be better than creating unnecessary interrupts. And the code would be more consistent across the different processors.

Franz-Peter

**Comment by tanner87661** [comment] 2019-02-16 15:22
Hi Franz-Peter

 

Yes, that was the first thing to try. It had no effect. The general rule for ISRs on the ESP32 is that they (as well as all other functions called from the ISR) must be in the RAM, not in the flash, or you will see crashes when using other flash intensive stuff like for example SPIFFS file server (there is actually plenty of documentation on this problem). And attach/detach interrupt is not a function in RAM and takes some of time, therefore the problems.

Personally I am also not sure if the solution with changing the interrupt trigger is really good on the AVR platform. Someone should investigate how many cycles it cost to reattach the interrupt compared to returning from an unused interrupt immediately.

Hans

**Comment by MicroBahner** [comment] 2019-02-16 16:11
Hi Hans,
ok, so we have to stick to your solution.

> Personally I am also not sure if the solution with changing the interrupt trigger is really good on the AVR platform. Someone should investigate how many cycles it cost to reattach the interrupt compared to returning from an unused interrupt immediately.

Reattaching the interrupt does not occur in every interrupt, but only 2 times during a whole DCC packet. Unnecessary interrupts occur in nearly every bit, because the change irq is only used during a short period after detecting the preamble and searching for the startbit.

Franz-Peter

**Comment by kiwi64ajs** [comment] 2019-02-16 20:34
I might dig into the Arduino core library and see how hard it might be to just change the edge as opposed to detach/attach. It’d be a hack but...

A potentially better solution on the ESP32 is to use the RMT peripheral but that is a huge change.

Alex

**Comment by MicroBahner** [comment] 2019-02-17 21:49
Hi Alex, Hi Hans,
now I created a branch with the ESP32 specific changes of Hans. If 'ESP32' is defined it should  work as Hans proposed with all his changes. If 'ESP32' is not defined it should create a code just like the current master branch. A first test on my standard-Decoder HW worked. I will do some more testing the next days for AVR and STM32F1. Unfortunately I don't have a ESP32. So I'd like to ask Hans to test this code. It is in  the branch [ESP32-processor-specific](https://github.com/MicroBahner/NmraDcc/tree/ESP32-processor-specific) of my fork of the lib. If the tests are successfull I can create a pull request.

In this solution only the ESP32 will create that many unnecessary Interrupts. I hope they don't matter as much as on AVR.

--------------------------
A complete other solution that we can discuss might be, to avoid changing the interrupt trigger in the ISR and do it outside in the 'normal' sketch. As I understand, that schould work on ESP32 too.
Which trigger - rising or falling - is needed depends on the polarity of the DCC signal. As it is now, this is determined after the preamble when waiting for the startbit of a packet. The CHANGE irq is needed to do this until startbit and polarity are detected. But obviously - if you determined the polarity once it will not really change between every packet. Usually it changes only if you unplug and plug in the other way round. On the other hand - if you are on the false edge, you will never get a correct packet. Either you get a checksum error or you get no packet at all.
So my idea is: In the process method you check every second whether you received at least one correct package within the last second. If so, everything is ok and nothing has to be done. If you received only checksum errors or no packet at all, then change the IRQ trigger to the other edge and wait for the next second. Of course when applying the DCC signal the first time ore changing the polarity it may last 1 or 2 seconds until packets are detected correctly.
What do you think - might that be a solution for all processors?  Or is there an error in my reasoning?

**Comment by tanner87661** [comment] 2019-02-17 23:01
Hi Franz-Peter

 

Thanks for working on this.

 

I will give it a try, probably tomorrow, but from looking over it I think it should work except that line 1395 should be eliminated. If the interrupt is not changing, it does not need to be reattached.

 

Changing the interrupt type from outside might work, I think.

 

Polarity changes can actually be more frequent than what you describe. Think about a decoder that sits behind an auto-reversing section.

 

Also, how does this code react in case of zero-stretched zero bits, when using an analog locomotive?

 

A completely different approach might be to use change type interrupt but only record signal level and last eight bits of micros() into a buffer so that the interrupt returns fast. Then use the process routine (or in the case of RTOS even define  task for this) to do the analysis of the stream and decoding. I remember back in 1997 I fed the DCC stream into a sound card and decoded it from the WAV stream using that approach. At the time I think it was the first PC based DCC decoder running on a 386 under Windows 3.11 I believe it was. I called it DCC Sniffer and even got a cease and desist letter from a company who was marketing a product called Network Sniffer, because they had a TM on the term Sniffer ;-) Tempi passati.

 

Hans

**Comment by MicroBahner** [comment] 2019-02-18 10:07
Hi Hans,

> except that line 1395 should be eliminated.

Really? Line 1395 is the inital attach in the ini-function after starting the sketch. I think you cannot omit this ?

> Polarity changes can actually be more frequent than what you describe. Think about a decoder that sits behind an auto-reversing section.

Yes, you are right. Especially in a loco decoder this can obviously happen. And 1 second to recognize the polarity change is definitely to long in this case. Maybe we can reduce the time to 100ms. But with this in mind I have doubts whether my idea will work.

> Also, how does this code react in case of zero-stretched zero bits, when using an analog locomotive?

That should be no problem, Stretched bits are recognized as zero bits. 

> A completely different approach might be to use change type interrupt but only record signal level and last eight bits of micros() into a buffer so that the interrupt returns fast.

I think that's really RAM-consuming. And RAM is a rare resource on an AVR

Franz-Peter

**Comment by tanner87661** [comment] 2019-02-18 16:26
You’re right, I mistook it for a line in the ISR.

 

So I gave it a try this morning and it works as expected. It properly decodes standard accessory commands as well as signal commands. Good work.

Hans

**Comment by kiwi64ajs** [comment] 2019-02-21 19:46
I've merged Franz-Peter PR into Master, so if we can try it out on our different hardware and report success, then I'll Tag it as release 2.0.1 so it becomes available to the Arduino Library Manager

**Comment by MicroBahner** [comment] 2019-02-23 08:10
Hi Alex,
my tests with AVR and STM32F1 have been successful.
Franz-Peter

**Comment by MicroBahner** [comment] 2019-05-01 20:53
Hi Alex,
before releasing the new version we should change the following line in nmradcc.h:
`#define NMRADCC_VERSION     200     // Version 2.0.0
`
to 
`#define NMRADCC_VERSION     201     // Version 2.0.1
`
Franz-Peter

**Comment by kiwi64ajs** [comment] 2019-05-01 23:29
Hmmm… ok

Its looks like I have some merge conflicts now…

Will get one of my devs to help me sort it…

Alex

**Comment by kiwi64ajs** [comment] 2019-05-02 07:42
I believe I've sorted the merge conflicts and merged the ESP32 changes into master.

Before I tag the repo to 2.0.1 it would be good if you guys could double check what I've done in case I messed up a merge.

Just noticed one potential difference.
At line 1510 here: https://github.com/mrrwa/NmraDcc/blob/master/NmraDcc.cpp#L1510 we have:

    #ifdef ESP32
        portENTER_CRITICAL(&mux);
    #else
        noInterrupts();
    #endif
        Msg = DccRx.PacketCopy ;
        DccRx.DataReady = 0 ;

    #ifdef ESP32
        portEXIT_CRITICAL(&mux);
    #else
        interrupts();
    #endif

whereas at line: 567 here: https://github.com/mrrwa/NmraDcc/blob/master/NmraDcc.cpp#L567 we just have the ESP32 bit with no normal Arduino noInterrupts() / interrupts() calls:

    #ifdef ESP32
    	  portENTER_CRITICAL_ISR(&mux);
    #endif
          DccRx.PacketCopy = DccRx.PacketBuf ;
          DccRx.DataReady = 1 ;
    #ifdef ESP32
    	  portEXIT_CRITICAL_ISR(&mux);
    #endif

 Should these be added?

**Comment by MicroBahner** [comment] 2019-05-02 09:22
Hi Alex,
in line 567 we are within the Dcc-Interrupt, and this interrupt is protected by a flag against interrupting itself. Normally this should never happen, but as you know, we had problems with glitches and that's the reason why this flag was implemented, From normal Arduino point of view there is no need to do a nointerrupt()/interrupt() call at this point.
I don't know the ESP32 and don't even have one. May be it isn't necessary for the ESP32 too.

Franz-Peter

**Comment by kiwi64ajs** [comment] 2019-05-02 09:41
Hi Franz-Peter

> On 2/05/2019, at 9:22 PM, Franz-Peter <notifications@github.com> wrote:
> 
> Hi Alex,
> in line 567 we are within the Dcc-Interrupt, and this interrupt is protected by a flag against interrupting itself. Normally this should never happen, but as you know, we had problems with glitches and that's the reason why this flag was implemented, From normal Arduino point of view there is no need to do a nointerrupt()/interrupt() call at this point.
> I don't know the ESP32 and don't even have one. May be it isn't necessary for the ESP32 too.
> 
Ah ok - that makes sense.

The issue with the ESP32 is the dual core potential for concurrent access that needs to protected against.

So I think we’re ok.

If you can verify its still working ok then I can tag the repo and release the updated version to the Arduino Library Manager

Alex

**Comment by MicroBahner** [comment] 2019-05-02 09:49
Hi Alex,
ok, I'll do some tests the next days.
Franz-Peter

**Comment by gbglacier** [comment] 2019-05-02 16:18
Hi All,
    Do you guys realize there is more than one implementation of an
      ESP32?
    Expressif (the creators) defined a "ESP32 dev" module that many use,
    but there are several other versions (some better in my opinion like
    the Ezsbc.com board).
    The point is that they do not have a "standard" pinout. In this case
    it does not mean
    physical pin layout, but rather which pins are actually brought out
    to edge points.
    
    So which are you allowing for? Or do you account for all variations?
    Have fun!  :-)
    Best regards,
    Geoff Bunza
    
    
    On 5/2/2019 2:41 AM, Alex Shepherd
      wrote:
    
    Hi
      Franz-Peter
      
      > On 2/05/2019, at 9:22 PM, Franz-Peter
      <notifications@github.com> wrote:
      > 
      > Hi Alex,
      > in line 567 we are within the Dcc-Interrupt, and this
      interrupt is protected by a flag against interrupting itself.
      Normally this should never happen, but as you know, we had
      problems with glitches and that's the reason why this flag was
      implemented, From normal Arduino point of view there is no need to
      do a nointerrupt()/interrupt() call at this point.
      > I don't know the ESP32 and don't even have one. May be it
      isn't necessary for the ESP32 too.
      > 
      Ah ok - that makes sense.
      
      The issue with the ESP32 is the dual core potential for concurrent
      access that needs to protected against.
      
      So I think we’re ok.
      
      If you can verify its still working ok then I can tag the repo and
      release the updated version to the Arduino Library Manager
      
      Alex
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrrwa/NmraDcc","title":"mrrwa/NmraDcc","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mrrwa/NmraDcc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kiwi64ajs in #22: Hi Franz-Peter\n\n\u003e On 2/05/2019, at 9:22 PM, Franz-Peter \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e Hi Alex,\n\u003e in line 567 we are within the Dcc-Interrupt, and this interrupt is protected by a flag against interrupting itself. Normally this should never happen, but as you know, we had problems with glitches and that's the reason why this flag was implemented, From normal Arduino point of view there is no need to do a nointerrupt()/interrupt() call at this point.\n\u003e I don't know the ESP32 and don't even have one. May be it isn't necessary for the ESP32 too.\n\u003e \nAh ok - that makes sense.\n\nThe issue with the ESP32 is the dual core potential for concurrent access that needs to protected against.\n\nSo I think we’re ok.\n\nIf you can verify its still working ok then I can tag the repo and release the updated version to the Arduino Library Manager\n\nAlex "}],"action":{"name":"View Issue","url":"https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175"}}}
      [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175",

"url": "https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
    
    
    -- 
      
      
      
      
      
      
      
      
      
      


      
        Geoff Bunza
        gbglacier@comcast.net
        scalemodelanimation.com

**Comment by kiwi64ajs** [comment] 2019-05-02 20:09
Hi Geoff

This relates to enabling compiler support for ESP32 generally and not just for a specific ESP32 board. It’s ESP32 vs AVR vs. STM32

Alex

**Comment by gbglacier** [comment] 2019-05-03 00:22
Understood Alex. I thought this might be worth
      noting. 
      I jst published an ESP32 design (throttle not decoder) and some
      modelers
      did not heed my warning about differences in ESP32's.
      Have fun!  :-)
      Best regards,
      Geoff
      
    
    On 5/2/2019 1:09 PM, Alex Shepherd
      wrote:
    
    Hi
      Geoff
      
      This relates to enabling compiler support for ESP32 generally and
      not just for a specific ESP32 board. It’s ESP32 vs AVR vs. STM32
      
      Alex 
      
      Sent from my iPad
      
      > On 3/05/2019, at 4:18 AM, Geoff Bunza
      <notifications@github.com> wrote:
      > 
      > 
      > 
      > 
      > 
      > 
      > Hi All, 
      > Do you guys realize there is more than one implementation of
      an 
      > ESP32? 
      > Expressif (the creators) defined a "ESP32 dev" module that
      many use, 
      > but there are several other versions (some better in my
      opinion like 
      > the Ezsbc.com board). 
      > The point is that they do not have a "standard" pinout. In
      this case 
      > it does not mean 
      > physical pin layout, but rather which pins are actually
      brought out 
      > to edge points. 
      > 
      > So which are you allowing for? Or do you account for all
      variations? 
      > Have fun! :-) 
      > Best regards, 
      > Geoff Bunza 
      > 
      > 
      > On 5/2/2019 2:41 AM, Alex Shepherd 
      > wrote: 
      > 
      > Hi 
      > Franz-Peter 
      > 
      > > On 2/05/2019, at 9:22 PM, Franz-Peter 
      > <notifications@github.com> wrote: 
      > > 
      > > Hi Alex, 
      > > in line 567 we are within the Dcc-Interrupt, and this 
      > interrupt is protected by a flag against interrupting itself.
      
      > Normally this should never happen, but as you know, we had 
      > problems with glitches and that's the reason why this flag
      was 
      > implemented, From normal Arduino point of view there is no
      need to 
      > do a nointerrupt()/interrupt() call at this point. 
      > > I don't know the ESP32 and don't even have one. May be
      it 
      > isn't necessary for the ESP32 too. 
      > > 
      > Ah ok - that makes sense. 
      > 
      > The issue with the ESP32 is the dual core potential for
      concurrent 
      > access that needs to protected against. 
      > 
      > So I think we’re ok. 
      > 
      > If you can verify its still working ok then I can tag the
      repo and 
      > release the updated version to the Arduino Library Manager 
      > 
      > Alex 
      > — 
      > You are receiving this because you are subscribed to this 
      > thread. 
      > Reply to this email directly, view it on GitHub, or mute the
      thread. 
      >
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrrwa/NmraDcc","title":"mrrwa/NmraDcc","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open
      in
GitHub","url":"https://github.com/mrrwa/NmraDcc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kiwi64ajs
      in #22: Hi Franz-Peter\n\n\u003e On 2/05/2019, at 9:22 PM,
      Franz-Peter \u003cnotifications@github.com\u003e wrote:\n\u003e
      \n\u003e Hi Alex,\n\u003e in line 567 we are within the
      Dcc-Interrupt, and this interrupt is protected by a flag against
      interrupting itself. Normally this should never happen, but as you
      know, we had problems with glitches and that's the reason why this
      flag was implemented, From normal Arduino point of view there is
      no need to do a nointerrupt()/interrupt() call at this
      point.\n\u003e I don't know the ESP32 and don't even have one. May
      be it isn't necessary for the ESP32 too.\n\u003e \nAh ok - that
      makes sense.\n\nThe issue with the ESP32 is the dual core
      potential for concurrent access that needs to protected
      against.\n\nSo I think we’re ok.\n\nIf you can verify its still
      working ok then I can tag the repo and release the updated version
      to the Arduino Library Manager\n\nAlex "}],"action":{"name":"View
Issue","url":"https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175"}}}
      
      > [ 
      > 
      > { 
      > 
      > "@context": "http://schema.org", 
      > 
      > "@type": "EmailMessage", 
      > 
      > "potentialAction": { 
      > 
      > "@type": "ViewAction", 
      > 
      > "target":
      "https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175",
      
      > 
      > "url":
      "https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175",
      
      > 
      > "name": "View Issue" 
      > 
      > }, 
      > 
      > "description": "View this Issue on GitHub", 
      > 
      > "publisher": { 
      > 
      > "@type": "Organization", 
      > 
      > "name": "GitHub", 
      > 
      > "url": "https://github.com" 
      > 
      > } 
      > 
      > } 
      > 
      > ] 
      > 
      > 
      > -- 
      > 
      > 
      > 
      > 
      > 
      > 
      > 
      > 
      > 
      > 
      >  
      > 
      > 
      > Geoff Bunza 
      > gbglacier@comcast.net 
      > scalemodelanimation.com 
      > 
      > —
      > You are receiving this because you commented.
      > Reply to this email directly, view it on GitHub, or mute the
      thread.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrrwa/NmraDcc","title":"mrrwa/NmraDcc","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mrrwa/NmraDcc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kiwi64ajs in #22: Hi Geoff\n\nThis relates to enabling compiler support for ESP32 generally and not just for a specific ESP32 board. It’s ESP32 vs AVR vs. STM32\n\nAlex  \n\nSent from my iPad\n\n\u003e On 3/05/2019, at 4:18 AM, Geoff Bunza \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e Hi All, \n\u003e Do you guys realize there is more than one implementation of an \n\u003e ESP32? \n\u003e Expressif (the creators) defined a \"ESP32 dev\" module that many use, \n\u003e but there are several other versions (some better in my opinion like \n\u003e the Ezsbc.com board). \n\u003e The point is that they do not have a \"standard\" pinout. In this case \n\u003e it does not mean \n\u003e physical pin layout, but rather which pins are actually brought out \n\u003e to edge points. \n\u003e \n\u003e So which are you allowing for? Or do you account for all variations? \n\u003e Have fun!  :-) \n\u003e Best regards, \n\u003e Geoff Bunza \n\u003e \n\u003e \n\u003e On 5/2/2019 2:41 AM, Alex Shepherd \n\u003e wrote: \n\u003e \n\u003e Hi \n\u003e Franz-Peter \n\u003e \n\u003e \u003e On 2/05/2019, at 9:22 PM, Franz-Peter \n\u003e \u003cnotifications@github.com\u003e wrote: \n\u003e \u003e \n\u003e \u003e Hi Alex, \n\u003e \u003e in line 567 we are within the Dcc-Interrupt, and this \n\u003e interrupt is protected by a flag against interrupting itself. \n\u003e Normally this should never happen, but as you know, we had \n\u003e problems with glitches and that's the reason why this flag was \n\u003e implemented, From normal Arduino point of view there is no need to \n\u003e do a nointerrupt()/interrupt() call at this point. \n\u003e \u003e I don't know the ESP32 and don't even have one. May be it \n\u003e isn't necessary for the ESP32 too. \n\u003e \u003e \n\u003e Ah ok - that makes sense. \n\u003e \n\u003e The issue with the ESP32 is the dual core potential for concurrent \n\u003e access that needs to protected against. \n\u003e \n\u003e So I think we’re ok. \n\u003e \n\u003e If you can verify its still working ok then I can tag the repo and \n\u003e release the updated version to the Arduino Library Manager \n\u003e \n\u003e Alex \n\u003e — \n\u003e You are receiving this because you are subscribed to this \n\u003e thread. \n\u003e Reply to this email directly, view it on GitHub, or mute the thread. \n\u003e {\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/mrrwa/NmraDcc\",\"title\":\"mrrwa/NmraDcc\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://github.githubassets.com/images/email/message_cards/header.png\",\"avatar_image_url\":\"https://github.githubassets.com/images/email/message_cards/avatar.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/mrrwa/NmraDcc\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@kiwi64ajs in #22: Hi Franz-Peter\\n\\n\\u003e On 2/05/2019, at 9:22 PM, Franz-Peter \\u003cnotifications@github.com\\u003e wrote:\\n\\u003e \\n\\u003e Hi Alex,\\n\\u003e in line 567 we are within the Dcc-Interrupt, and this interrupt is protected by a flag against interrupting itself. Normally this should never happen, but as you know, we had problems with glitches and that's the reason why this flag was implemented, From normal Arduino point of view there is no need to do a nointerrupt()/interrupt() call at this point.\\n\\u003e I don't know the ESP32 and don't even have one. May be it isn't necessary for the ESP32 too.\\n\\u003e \\nAh ok - that makes sense.\\n\\nThe issue with the ESP32 is the dual core potential for concurrent access that needs to protected against.\\n\\nSo I think we’re ok.\\n\\nIf you can verify its still working ok then I can tag the repo and release the updated version to the Arduino Library Manager\\n\\nAlex \"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175\"}}} \n\u003e [ \n\u003e \n\u003e { \n\u003e \n\u003e \"@context\": \"http://schema.org\", \n\u003e \n\u003e \"@type\": \"EmailMessage\", \n\u003e \n\u003e \"potentialAction\": { \n\u003e \n\u003e \"@type\": \"ViewAction\", \n\u003e \n\u003e \"target\": \"https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175\", \n\u003e \n\u003e \"url\": \"https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488612175\", \n\u003e \n\u003e \"name\": \"View Issue\" \n\u003e \n\u003e }, \n\u003e \n\u003e \"description\": \"View this Issue on GitHub\", \n\u003e \n\u003e \"publisher\": { \n\u003e \n\u003e \"@type\": \"Organization\", \n\u003e \n\u003e \"name\": \"GitHub\", \n\u003e \n\u003e \"url\": \"https://github.com\" \n\u003e \n\u003e } \n\u003e \n\u003e } \n\u003e \n\u003e ] \n\u003e \n\u003e \n\u003e -- \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \u003c!-- \n\u003e /* Font Definitions */ \n\u003e @font-face \n\u003e {font-family:\"Cambria Math\"; \n\u003e panose-1:2 4 5 3 5 4 6 3 2 4; \n\u003e mso-font-charset:1; \n\u003e mso-generic-font-family:roman; \n\u003e mso-font-format:other; \n\u003e mso-font-pitch:variable; \n\u003e mso-font-signature:0 0 0 0 0 0;} \n\u003e @font-face \n\u003e {font-family:Calibri; \n\u003e panose-1:2 15 5 2 2 2 4 3 2 4; \n\u003e mso-font-charset:0; \n\u003e mso-generic-font-family:swiss; \n\u003e mso-font-pitch:variable; \n\u003e mso-font-signature:-536859905 -1073732485 9 0 511 0;} \n\u003e /* Style Definitions */ \n\u003e p.MsoNormal, li.MsoNormal, div.MsoNormal \n\u003e {mso-style-unhide:no; \n\u003e mso-style-qformat:yes; \n\u003e mso-style-parent:\"\"; \n\u003e margin-top:0in; \n\u003e margin-right:0in; \n\u003e margin-bottom:10.0pt; \n\u003e margin-left:0in; \n\u003e line-height:115%; \n\u003e mso-pagination:widow-orphan; \n\u003e font-size:11.0pt; \n\u003e font-family:\"Calibri\",\"sans-serif\"; \n\u003e mso-ascii-font-family:Calibri; \n\u003e mso-ascii-theme-font:minor-latin; \n\u003e mso-fareast-font-family:Calibri; \n\u003e mso-fareast-theme-font:minor-latin; \n\u003e mso-hansi-font-family:Calibri; \n\u003e mso-hansi-theme-font:minor-latin; \n\u003e mso-bidi-font-family:\"Times New Roman\"; \n\u003e mso-bidi-theme-font:minor-bidi;} \n\u003e a:link, span.MsoHyperlink \n\u003e {mso-style-priority:99; \n\u003e color:blue; \n\u003e mso-themecolor:hyperlink; \n\u003e text-decoration:underline; \n\u003e text-underline:single;} \n\u003e a:visited, span.MsoHyperlinkFollowed \n\u003e {mso-style-noshow:yes; \n\u003e mso-style-priority:99; \n\u003e color:purple; \n\u003e mso-themecolor:followedhyperlink; \n\u003e text-decoration:underline; \n\u003e text-underline:single;} \n\u003e span.SpellE \n\u003e {mso-style-name:\"\"; \n\u003e mso-spl-e:yes;} \n\u003e .MsoChpDefault \n\u003e {mso-style-type:export-only; \n\u003e mso-default-props:yes; \n\u003e font-size:10.0pt; \n\u003e mso-ansi-font-size:10.0pt; \n\u003e mso-bidi-font-size:10.0pt; \n\u003e mso-ascii-font-family:Calibri; \n\u003e mso-ascii-theme-font:minor-latin; \n\u003e mso-fareast-font-family:Calibri; \n\u003e mso-fareast-theme-font:minor-latin; \n\u003e mso-hansi-font-family:Calibri; \n\u003e mso-hansi-theme-font:minor-latin; \n\u003e mso-bidi-font-family:\"Times New Roman\"; \n\u003e mso-bidi-theme-font:minor-bidi;} \n\u003e @page Section1 \n\u003e {size:8.5in 11.0in; \n\u003e margin:1.0in 1.0in 1.0in 1.0in; \n\u003e mso-header-margin:.5in; \n\u003e mso-footer-margin:.5in; \n\u003e mso-paper-source:0;} \n\u003e div.Section1 \n\u003e {page:Section1;} \n\u003e --\u003e \n\u003e \n\u003e \n\u003e Geoff Bunza \n\u003e gbglacier@comcast.net \n\u003e scalemodelanimation.com \n\u003e  \n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n"}],"action":{"name":"View Issue","url":"https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488814140"}}}
      [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488814140",

"url": "https://github.com/mrrwa/NmraDcc/issues/22#issuecomment-488814140",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
    
    
    -- 
      
      
      
      
      
      
      
      
      
      


      
        Geoff Bunza
        gbglacier@comcast.net
        scalemodelanimation.com

**Comment by kiwi64ajs** [comment] 2019-05-03 02:07
> Understood Alex. I thought this might be worth 
> noting. 
> I jst published an ESP32 design (throttle not decoder) and some 
> modelers 
> did not heed my warning about differences in ESP32's. 

Ah, yes… I guess with the various sources not being too concerned with providing any details or documentation etc its a bit of a murky pond huh…

BTW I’ve finally merged in some ESP32 changes into the NmraDcc library. It compiles and I’m pretty sure I got it right but had to manually resolve conflicts, so if you get a change, it would be helpful if you could check version 2.0.1 in master of the library on some of your AVR and ESP32 project.

Alex

**Comment by kiwi64ajs** [comment] 2019-10-28 05:52
I think this is done

**Closed as completed** 2019-10-28 05:52 UTC
